# -*- coding: utf-8 -*-
"""RAG PIPELINE USING LANGCHAIN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u7kcD8x-QRpKQV9cgkteS_aVYZHMI-XT
"""

!pip install -U langchain langchain-google-genai langchain-community langchain-chroma langchain-text-splitters

from google.colab import userdata
import os

os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')

from pathlib import Path

BASE_DIR = Path("data/policies")
BASE_DIR.mkdir(parents=True, exist_ok=True)

documents = {
    "return_policy.md": """
# Return Policy
Customers can return most products within 10 days of delivery.
Electronics such as headphones, keyboards, smart watches, and mobile accessories
can be returned only within 7 days of delivery.
Products must be unused, undamaged, and returned with original packaging.
Items marked as final sale cannot be returned.
""",
    "refund_policy.md": """
# Refund Policy
Refunds are initiated after the returned product passes quality inspection.
For prepaid orders, the refund is usually processed within 5 to 7 business days.
Shipping charges are non-refundable unless the product was damaged, defective,
or incorrectly delivered.
""",
    "shipping_policy.md": """
# Shipping Policy
Standard delivery usually takes 3 to 5 business days in metro cities.
Delivery to remote areas may take 7 to 10 business days.
If delivery fails because the customer is unavailable, the courier partner will
make up to 2 additional delivery attempts.
""",
    "warranty_policy.md": """
# Warranty Policy
Electronic accessories come with a 6-month limited warranty.
Home appliances usually come with a 1-year manufacturer warranty.
Warranty does not cover physical damage, water damage, misuse, or unauthorized repair.
""",
    "cancellation_policy.md": """
# Cancellation Policy
Customers can cancel an order before it is shipped.
Once the order is shipped, cancellation is not allowed.
Orders containing personalized or made-to-order products cannot be cancelled
after production starts.
""",
}

for filename, content in documents.items():
    (BASE_DIR / filename).write_text(content.strip(), encoding="utf-8")

print("Sample corpus created:", list(documents.keys()))

from langchain_community.document_loaders import DirectoryLoader, TextLoader

DATA_DIR = Path("data/policies")

loader = DirectoryLoader(
    path=str(DATA_DIR),
    glob="**/*.md",
    loader_cls=TextLoader,
    loader_kwargs={"encoding": "utf-8"},
)

docs = loader.load()
print(f"Loaded {len(docs)} documents")
for doc in docs:
    print("-", doc.metadata.get("source"))

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=800,
    chunk_overlap=120,
    add_start_index=True,
)

chunks = text_splitter.split_documents(docs)
print(f"Original documents: {len(docs)}")
print(f"Generated chunks: {len(chunks)}")

import shutil
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_chroma import Chroma

CHROMA_DIR = Path("chroma_db")
COLLECTION_NAME = "ecommerce_policy_docs"

if CHROMA_DIR.exists():
    shutil.rmtree(CHROMA_DIR)

embeddings = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-001")

vector_store = Chroma(
    collection_name=COLLECTION_NAME,
    embedding_function=embeddings,
    persist_directory=str(CHROMA_DIR),
)

ids = vector_store.add_documents(documents=chunks)
print("Indexing done. Chunks stored:", len(chunks))

retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 3},
)

query = "What is the return window for electronics?"
results = retriever.invoke(query)

for i, doc in enumerate(results, start=1):
    print(f"\nResult {i} — source: {doc.metadata.get('source')}")
    print(doc.page_content[:200])

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0)

def format_docs(docs):
    chunks_text = []
    for i, doc in enumerate(docs, start=1):
        source = doc.metadata.get("source", "unknown")
        chunks_text.append(f"Source {i}: {source}\n{doc.page_content}")
    return "\n\n".join(chunks_text)

prompt = ChatPromptTemplate.from_template("""
You are a helpful customer-support assistant.
Use ONLY the retrieved context to answer the user's question.

Rules:
1. If the answer is present, answer clearly.
2. If not, say: "I don't know based on the provided documents."
3. Mention the source file name wherever possible.

<context>
{context}
</context>

Question:
{question}

Answer:
""")

rag_chain = (
    {
        "context": retriever | format_docs,
        "question": RunnablePassthrough(),
    }
    | prompt
    | llm
    | StrOutputParser()
)

questions = [
    "What is the return window for electronics?",
    "How long does delivery take in metro cities?",
    "Can I cancel an order after it is shipped?",
    "Do electronic accessories have warranty?",
]

for q in questions:
    print("\n" + "="*80)
    print("Q:", q)
    print(rag_chain.invoke(q))