# -*- coding: utf-8 -*-
"""STATELESS/STATEFUL AGENTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bbMF6YXWgDeCCY6QmzvyCowxCNMKqnLX
"""

!pip install langchain_google_genai
!pip install langchain
!pip install langchain_core
!pip install langchain_classic

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')
print("Key loaded:", "GOOGLE_API_KEY" in os.environ)

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import AIMessage, HumanMessage
from langchain_core.tools import tool
from langchain_classic.agents import create_tool_calling_agent,AgentExecutor

#Dataset
ORDERS = {
    "ORD-101": {
        "status": "shipped",
        "city": "Delhi",
        "amount": 2500,
        "delivery_days": 2
    },
    "ORD-102": {
        "status": "cancelled",
        "city": "Bangalore",
        "amount": 4000,
        "delivery_days": 0
    },
    "ORD-103": {
        "status": "delivered",
        "city": "Mumbai",
        "amount": 1500,
        "delivery_days": 0
    }
}

@tool
def get_order_status(order_id: str) -> str:
    """Get the status of an order."""
    return ORDERS[order_id]["status"]

llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0)

prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        """
You are a helpful customer support agent.

Rules:
- If the user gives an order id, keep a note of it.
- If the user asks a query like "track the order" or "where is the order", use the order id from the input.
- Use tools when order status is required.
- If no order id is available, politely ask the user for the order id.
"""
    ),

    # The previous conversation messages (HumanMessage + AIMessage) will be appened to the chat_history and will be used by the LLM to retrieve the context.
    MessagesPlaceholder(variable_name="chat_history", optional=True),

    ("human", "{input}"),

    MessagesPlaceholder(variable_name="agent_scratchpad")
])

tools=[get_order_status]

agent=create_tool_calling_agent(llm=llm,prompt=prompt,tools=tools)

agent_executer=AgentExecutor(agent=agent,tools=tools)

def ask_agent(user_query:str):
  response=agent_executer.invoke({
      "input":user_query,
      "chat_history":[]
  })
  return response["output"]

#give memory
user_query=input("Enter your query: ")
print(ask_agent(user_query))

# ask about memory(will forget because stateless agent)
user_query=input("Enter your query: ")
print(ask_agent(user_query))

chat_history=[]

#statefull agent
def ask_agent(user_query:str):
  response=agent_executer.invoke({
      "input":user_query,
      "chat_history":[]
  })
  chat_history.append(HumanMessage(content=user_query))
  chat_history.append(AIMessage(content=response["output"]))
  return response["output"]

#now ask this keeps memory but a very big security breach issue in short its dumb

#we make it a little smart we create a store to store session ids which fetches from local the actual conv subject to id only"smarrrrt!"

from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_core.chat_history import InMemoryChatMessageHistory
store={}

def get_session_history(session_id:str):
  if session_id not in store:
    store[session_id]=[]
  return store[session_id]

agent_with_memory = RunnableWithMessageHistory(
    agent_executer,
    get_session_history,
    input_messages_key='input',
    history_messages_key="chat_history",
    output_messages_key="output"
)

def ask_agent(user_query:str,session_id:str):
  response=agent_with_memory.invoke(
      {"input":user_query},
      config={"configurable":{
          "session_id":session_id
      }}
  )
  return response["output"]

session_id = 'user-101'

print('Turn-1')
user_query = "My order id is ORD-101"
print("User query: ", user_query)
print("AI response: ", ask_agent(user_query, session_id))

print('Turn-2')
user_query = "Track it."
print("User query", user_query)
print("AI response: ", ask_agent(user_query, session_id))

session_id_1 = 'user-102'

print('Turn-1 for the new user.')
user_query = "Track it."
print("User query", user_query)
print("AI response: ", ask_agent(user_query, session_id_1))

#session id to memory relation can be nested too